name: Coverage
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dep
        run: yarn install
      - name: run test
        run: yarn test
      - name: Codecov upload
        uses: codecov/codecov-action@v1.0.15
        with:
          # Path to coverage file to upload
          file: ./coverage/coverage-final.json
          fail_ci_if_error: true
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dep
        run: yarn install
      - name: build package
        run: yarn build
  release:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'joshuaellis/react-tensorflow' && contains('refs/heads/master,refs/heads/beta,refs/heads/alpha',github.ref) && github.event_name == 'push' }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Install deps
        # this runs a build script so there is no dedicated build
        run: yarn install
      - name: Build
        run: yarn build
      - name: 🚀 Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 17
          extra_plugins: |
            @semantic-release/git
          branches: |
            [
              'master',
              {name: 'beta', prerelease: true},
              {name: 'alpha', prerelease: true}
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
